//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSVImport.DAL.edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportData
    {
        public System.Guid ID { get; set; }
        public int PaymentID { get; set; }
        public string AccountHolder { get; set; }
        public int BranchCode { get; set; }
        public long AccountNumber { get; set; }
        public int AccountType { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> EffectiveStatusDate { get; set; }
    }
}
